### ISSUE TITLE
Can't log a command if it has alot of NBT/ it has brackets {}

### ISSUE THREAD

**Issue by kerostampcrab** [OMGitzFROST/PlayerLogs#4]
The error: https://paste.sparked.host/razapobizi.properties

Maybe the command logging didn't work since it had {} brackets?
Of course this doesn't bother me, as I doubt anyone would be making commands like this, but it's something good to fix.

**Comment by OMGitzFROST** [comment]
Are you able to recreate this problem? What steps do you take?

It looks like another plugin is being used to execute the commands, perhaps allow me to know which plugin and i can download and try to recreate the steps myself. I understand this problem is of importance since it bars you from using the other plugin till i resolve this issue, i will work on this as soon as i get the information requested.

**Comment by kerostampcrab** [comment]
What? No, just Minecraft's own 'data' command. This will happen if it's a /give, a /summon, anything that includes alot of NBT that's inside brackets.

**Comment by OMGitzFROST** [comment]
So i have tried to recreate this error, the command i used was this
`/give OMGitzFROST diamond_sword{Enchantments:[{id:looting,lvl:1},{id:sharpness,lvl:5},{id:unbreaking,lvl:3}]} 1`

And the logger did log correctly logging this message
`[12/20/2021 00:12]: OMGitzFROST issued server command: /give OMGitzFROST diamond_sword{Enchantments:[{id:looting,lvl:1},{id:sharpness,lvl:5},{id:unbreaking,lvl:3}]} 1`

Any info as to how to recreate your error is highly appreciated, it helps better understand how to fix the problem
